//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class busticketbookingEntities : DbContext
    {
        public busticketbookingEntities()
            : base("name=busticketbookingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<location> location { get; set; }
        public virtual DbSet<location2> location2 { get; set; }
        public virtual DbSet<recommend> recommend { get; set; }
        public virtual DbSet<recommend_info> recommend_info { get; set; }
        public virtual DbSet<reservation> reservation { get; set; }
        public virtual DbSet<schedule> schedule { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
